package ff.run

import ff.run.ReportManifest

/**
 * Check that a strategy document reasons only from a current board.
 *
 * A plan is written against one auction board and then the model moves. Nothing about a stale figure looks
 * stale: prices that are half a season out of date read exactly like prices that are not, and a plan is
 * worst affected precisely where the model changed most. Worse, a plan that reaches behind the board for a
 * rule or a constant argues a point the board has already priced in, and pays for it twice.
 *
 * So three things are checked, and each is a different way of getting the same thing wrong.
 *
 * <b>Provenance.</b> The document names the model it was written against; every report it cites must have
 * been generated by that model. This is the one that catches wholesale drift, including in prose that no
 * checker can read.
 *
 * <b>Figures.</b> Any table under a {@code <!-- source: type -->} marker is looked up in that report,
 * column by column, so a transcription slip or a hand-edited number is caught and named.
 *
 * <b>Boundary.</b> Nothing in the document may name a model internal, an input file, or a source path. A
 * figure that needs one of those is a report column that does not exist yet, and the fix is to add it to
 * the board rather than to quote it into the plan.
 *
 * See docs/STRATEGY.md.
 */
class StrategyCheck {

    /**
     * Words a plan may use that no report carries, being ordinary football rather than model vocabulary.
     *
     * <b>This is the whole maintained list, and it is meant to stay this short.</b> What replaced the long
     * one is in {@link #checkVocabulary}: rather than enumerating the internals a plan may not name, the
     * check asks whether a technical-looking word appears anywhere in the reports the plan is written from.
     * A list of forbidden internals has to be told about every class and constant the model gains, and was
     * not — it went thirty names out of date and let a plan reason from the lineup evaluator, the cut
     * penalty and four input files without complaint. A list of permitted prose does not grow when the model
     * does.
     */
    static final List<String> PROSE = [
            'PPR', 'NFL', 'IR', 'EOD', 'ADP', 'FAAB', 'TBD',
    ].asImmutable() as List<String>

    /**
     * Data sources, which a plan has no business naming and which no report carries either.
     *
     * Kept by hand because they are lowercase words rather than the capitalised tokens
     * {@link #checkVocabulary} looks at, and because unlike model internals they are stable: the league has
     * had the same three sources since 2017.
     */
    static final List<String> SOURCES = ['nflverse', 'fantasypros', 'myfantasyleague'].asImmutable()

    /** Paths a plan must not cite, being the model's own workings rather than its output. */
    static final List<String> FORBIDDEN_PATHS = ['src/', 'docs/'].asImmutable() as List<String>

    /** All caps, three or more: the shape of a constant, and of a board column. */
    private static final String SCREAMING = /\b[A-Z][A-Z0-9_]{2,}\b/

    /** An internal capital: the shape of a class name, and of a good many surnames. */
    private static final String CAMEL = /\b[A-Z][a-z0-9]+(?:[A-Z][a-z0-9]*)+\b/

    /** A data file, which is never something a plan reasons from unless it is one of its own reports. */
    private static final String DATA_FILE = /\b[\w.]+\.(?:json|csv|tsv)\b/

    private static final String MODEL_MARKER = /<!--\s*model:\s*(\S+)\s*-->/
    private static final String SOURCE_MARKER = /<!--\s*source:\s*([^>]*?)\s*-->/

    static void main(String[] args) {
        if (args.length < 1 || args.length > 2) {
            System.err.println('Usage: StrategyCheck <document.md> [reports-dir]')
            System.exit(2)
        }
        File document = new File(args[0])
        if (!document.exists()) {
            System.err.println("No such document: $document")
            System.exit(2)
        }
        // No default league, because there is no default league. `reports` was one while the auction's
        // sheets sat at its root; it is now the parent of both and belongs to neither, and defaulting to it
        // reported a missing directory rather than an ambiguous one.
        if (args.length < 2) {
            File reportsRoot = new File('reports')
            List<String> leagues = (reportsRoot.listFiles() ?: [] as File[])
                    .findAll { it.isDirectory() }*.name.sort()
            System.err.println('Usage: StrategyCheck <document.md> <reports-dir>')
            System.err.println(leagues
                    ? "  which league's board is this plan held to? ${leagues.collect { "reports/$it" }}"
                    : '  no reports have been generated yet')
            System.exit(2)
        }
        File reportsDir = new File(args[1])

        // Before any figure is compared: is the board this plan is held to still the model's board? A plan
        // and a report generated by the same superseded commit agree with each other perfectly.
        List<String> stale = checkCurrent(declaredModel(document.readLines()))
        if (stale) {
            println "FAIL  $document"
            stale.each { println "  $it" }
            System.exit(1)
        }

        List<String> failures = check(document, reportsDir)
        if (failures) {
            println "FAIL  $document"
            failures.each { println "  $it" }
            System.exit(1)
        }
        println "OK    $document"
    }

    /**
     * Whether the model the plan was written against is still the model.
     *
     * <b>{@link #checkProvenance} asks the other question and neither is sufficient alone.</b> That one
     * checks a cited report was generated by the model the plan declares, which catches a plan held against
     * somebody else's board. This one catches the case that file opens by describing: a plan written against
     * one board, the model moving underneath it, and the plan still reading as current because it agrees
     * with a report that is exactly as out of date as it is. Same sha on both sides, every figure stale, and
     * nothing to say so.
     *
     * The same question {@link DocsCheck#checkProvenance} asks of the figures before holding the
     * documentation to them. It is asked here of the plan rather than of the reports because the plan is
     * what names a model; the reports are checked against that name a second time, per source.
     *
     * <b>Not an equality test against HEAD.</b> A plan is written, then commits land that touch only
     * documentation or tests, and the model has not moved — see {@link ReportManifest#modelMovedSince}.
     *
     * Kept out of {@link #check} deliberately. That method answers "does this document agree with these
     * files", which is a question about two things a caller supplies and is what the spec exercises against
     * boards it writes itself. This answers "is any of it still current", which is a question about the
     * repository, and belongs to the command rather than to the comparison.
     */
    static List<String> checkCurrent(String model) {
        if (!model) {
            // check() reports a missing marker with the sha to add, which is the more useful message.
            return []
        }
        Boolean moved = ReportManifest.modelMovedSince(model)
        if (moved == null) {
            return ["written against model $model, which this repository does not have — regenerate the " +
                            'reports and revisit the plan' as String]
        }
        if (moved) {
            // Which script regenerates them is the league's business and this does not know the league:
            // checkCurrent is asked about a sha alone. Naming one league's script here was harmless while
            // there was one, and became advice to run the wrong tool the moment there were two.
            return ["written against model $model and the model has moved since: regenerate this " +
                            "league's reports and work through what changed" as String]
        }
        // Last, because it is the one thing a sha cannot describe: the reports may be exactly what that
        // commit produced and still not be what the model would produce now.
        ReportManifest.modelIsDirty() ?
                ['the model has uncommitted changes under src/main, so no report describes what would ' +
                         'actually run — commit it and regenerate'] : []
    }

    /** Every way the document disagrees with the board, in the order they appear. */
    static List<String> check(File document, File reportsDir) {
        List<String> lines = document.readLines()
        List<String> failures = []
        failures.addAll(checkPaths(lines))

        String model = declaredModel(lines)
        if (!model) {
            failures << "no model declared: add a <!-- model: ${ReportManifest.currentModel()} --> marker"
            return failures
        }

        File yearDir = reportDirectory(document, reportsDir)
        if (!yearDir?.isDirectory()) {
            failures << "no reports directory for this document under $reportsDir"
            return failures
        }
        Map<String, ReportManifest.Stamp> stamps = ReportManifest.read(yearDir)
        if (!stamps) {
            failures << "$yearDir holds no ${ReportManifest.FILE_NAME}: regenerate the reports"
            return failures
        }

        failures.addAll(checkVocabulary(lines, yearDir))
        failures.addAll(checkTables(lines, model, yearDir, stamps))
        failures
    }

    /** The `<!-- model: sha -->` the document was written against. */
    static String declaredModel(List<String> lines) {
        for (String line : lines) {
            def matcher = line =~ MODEL_MARKER
            if (matcher.find()) {
                return matcher.group(1)
            }
        }
        null
    }

    /**
     * Which season's reports the document is about, taken from a four digit year in its name.
     *
     * Naming the year rather than declaring it keeps one less thing to hand-maintain, and a plan that does
     * not say which season it is for has a bigger problem than this check.
     */
    private static File reportDirectory(File document, File reportsDir) {
        def matcher = document.name =~ /(\d{4})/
        matcher.find() ? new File(reportsDir, matcher.group(1)) : null
    }

    /**
     * {@code salaries} or {@code outlook_13 key=PICK+POS} into the report and its options.
     *
     * The same grammar DocsCheck's figure markers use, deliberately. The two checks ask the same question of
     * two kinds of table and had grown two answers to it; a plan and a document should not have to be
     * written differently to say the same thing.
     */
    private static Map<String, String> parseMarker(String body) {
        List<String> parts = body.trim().split(/\s+/) as List
        Map<String, String> marker = [source: parts.first()]
        parts.drop(1).each { String part ->
            List<String> pair = part.split('=', 2) as List
            if (pair.size() == 2) {
                marker[pair[0]] = pair[1]
            }
        }
        marker
    }

    private static List<String> checkPaths(List<String> lines) {
        List<String> failures = []
        lines.eachWithIndex { String line, int index ->
            String prose = withoutMarkers(line)
            FORBIDDEN_PATHS.each { String path ->
                if (prose.contains(path)) {
                    failures << "line ${index + 1}: cites '$path', which is the model's workings, " +
                            'not its output'
                }
            }
            SOURCES.each { String source ->
                if (prose =~ /(?i)(?<![\w.\/])${java.util.regex.Pattern.quote(source)}(?![\w])/) {
                    failures << "line ${index + 1}: names '$source', which is where the model gets its " +
                            'data, not something the board reports'
                }
            }
        }
        failures
    }

    /**
     * Every technical-looking word in the plan has to be one the board actually uses.
     *
     * <b>Asked the other way round from how it used to be.</b> The old check held a list of model internals
     * a plan must not name, which meant every commit that added a class or a constant silently widened the
     * hole — and thirty of them had accumulated, so a plan could reason from the lineup evaluator, the cut
     * penalty, the kicker depth and four input files and come back clean. Nothing linked the list to the
     * model it was supposed to describe.
     *
     * So the question is inverted. A plan's legitimate vocabulary is every report generated for its season:
     * their column names, and every value in them — players, teams, owners, tiers, bands. Anything shaped
     * like a constant or a class name that appears in none of them is something the plan went behind the
     * board for, whether or not anybody thought to forbid it. New internals are covered the day they are
     * written, because they are covered by not being reports.
     *
     * <b>Every report for the season, not only the ones the plan marks with a source.</b> A plan names teams
     * and players in prose that cites no table, and holding its vocabulary to only the tables it cites would
     * reject that. The cost is that a word carried by a report the plan never opens is admitted too.
     *
     * The two shapes it looks at are all-caps runs and internal capitals, which is what a constant and a
     * class name look like. It is not lost on this check that a good many surnames are the second shape:
     * that is why the vocabulary is drawn from every value in every report rather than only from the
     * headings, and a player who appears on no report is one a plan has no business reasoning about anyway.
     */
    private static List<String> checkVocabulary(List<String> lines, File yearDir) {
        Set<String> vocabulary = vocabularyOf(yearDir)
        Set<String> reportFiles = (yearDir.listFiles() ?: [] as File[]).collect { it.name } as Set
        List<String> failures = []
        lines.eachWithIndex { String line, int index ->
            String prose = withoutMarkers(line)
            (prose =~ DATA_FILE).each { String file ->
                if (!reportFiles.contains(file)) {
                    failures << "line ${index + 1}: reads '$file', which is a model input rather than one " +
                            'of this plan\'s reports'
                }
            }
            String withoutFiles = prose.replaceAll(DATA_FILE, ' ')
            ([(withoutFiles =~ SCREAMING).collect { it }, (withoutFiles =~ CAMEL).collect { it }]
                    .flatten() as List<String>).unique().each { String token ->
                if (!PROSE.contains(token) && !vocabulary.contains(token.toUpperCase()) &&
                        !isRankShorthand(token, vocabulary)) {
                    failures << "line ${index + 1}: names '$token', which no report carries — if the plan " +
                            'needs it, it is a missing board column rather than a licence to reach behind'
                }
            }
        }
        failures
    }

    /**
     * Everything the boards for this season actually say: headings and values alike.
     *
     * Values and not just headings, because most of what a plan legitimately writes in capitals is data — a
     * player, a team, an owner, a tier band. Upper-cased on both sides so the check is about whether the
     * board knows the word, not about how the plan happened to capitalise it.
     */
    private static Set<String> vocabularyOf(File yearDir) {
        Set<String> vocabulary = [] as Set<String>
        (yearDir.listFiles() ?: [] as File[])
                .findAll { it.name.endsWith('.tsv') || it.name.endsWith('.csv') }
                .each { File report ->
                    report.readLines().each { String line ->
                        line.split(/[\t,]/).each { String cell ->
                            cell.split(/[^A-Za-z0-9_.\']+/).each { String word ->
                                if (word) {
                                    vocabulary << word.toUpperCase()
                                }
                            }
                        }
                    }
                }
        vocabulary
    }

    /**
     * A position and a rank run together, which is how anybody discussing this league actually writes.
     *
     * QB2 and WR38 are on no board as literal strings — they are a {@code POS} cell and a {@code RANK} cell
     * side by side — but they are the plainest shorthand in the game and a check that rejected them would be
     * one nobody could write a plan under. Allowed by derivation rather than by listing: the letters have to
     * be something the board itself uses, so QB2 passes and FOO2 does not, and a position the league adds
     * later needs nothing done to it.
     */
    private static boolean isRankShorthand(String token, Set<String> vocabulary) {
        def matcher = token =~ /^([A-Za-z]{1,3})(\d{1,3})$/
        matcher.matches() && vocabulary.contains((matcher.group(1) as String).toUpperCase())
    }

    /**
     * A marker names a report type or a path, which is the sanctioned way to do so, so its own text is not
     * held to the boundary.
     *
     * <b>The comment is removed rather than the line skipped.</b> Skipping meant anything sharing a line
     * with a marker was exempt too, so a plan could write its way out of the boundary check by putting a
     * marker in front of whatever it wanted to say. The marker is what is sanctioned, not its neighbours.
     */
    private static String withoutMarkers(String line) { line.replaceAll(/<!--.*?-->/, ' ') }

    /**
     * Verify every table under a source marker against the report it names.
     *
     * The table's first column names the report column its rows are keyed by, and every other heading that
     * matches a report column is checked. Headings that match nothing are the plan's own commentary and are
     * left alone, so a table can carry a note or a running total without having to be understood here.
     */
    private static List<String> checkTables(List<String> lines, String model, File yearDir,
                                            Map<String, ReportManifest.Stamp> stamps) {
        List<String> failures = []
        Set<String> provenanceChecked = []
        Map<String, List<Map<String, String>>> cache = [:]
        String source = null
        String sourceKey = null
        List<String> headings = null

        for (int i = 0; i < lines.size(); i++) {
            String line = lines[i]
            def sourceMatcher = line =~ SOURCE_MARKER
            if (sourceMatcher.find()) {
                // `salaries` or `outlook_13 key=PICK+POS`, the same grammar DocsCheck's markers use.
                Map<String, String> marker = parseMarker(sourceMatcher.group(1))
                source = marker.source
                sourceKey = marker.key
                headings = null
                if (provenanceChecked.add(source)) {
                    failures.addAll(checkProvenance(source, model, stamps, i + 1))
                }
                continue
            }
            if (!source) {
                continue
            }
            if (!isTableRow(line)) {
                // A blank line between the marker and its table is fine; anything else ends the table.
                if (line.trim() && headings != null) {
                    source = null
                    sourceKey = null
                }
                continue
            }
            List<String> cells = cells(line)
            if (headings == null) {
                headings = cells
                continue
            }
            if (isDivider(cells)) {
                continue
            }
            failures.addAll(checkRow(source, sourceKey, yearDir, headings, cells, i + 1, cache))
        }
        failures
    }

    private static List<String> checkProvenance(String source, String model,
                                                Map<String, ReportManifest.Stamp> stamps, int line) {
        ReportManifest.Stamp stamp = stamps[source]
        if (!stamp) {
            return ["line $line: cites '$source', which has not been generated for this season"]
        }
        if (stamp.dirty) {
            return ["line $line: '$source' was generated from an uncommitted model ($stamp.model), " +
                            'so nothing can be checked against it']
        }
        if (stamp.sha() != model) {
            return ["line $line: written against model $model but '$source' was generated by " +
                            "${stamp.sha()} — regenerate the report and revisit the plan"]
        }
        []
    }

    private static List<String> checkRow(String source, String sourceKey, File yearDir, List<String> headings,
                                         List<String> cells, int line,
                                         Map<String, Map<String, Map<String, String>>> cache) {
        List<Map<String, String>> report = report(yearDir, source, cache)
        if (report == null) {
            return ["line $line: no report file for '$source'"]
        }
        if (!report) {
            return ["line $line: the $source board holds no rows"]
        }
        List<String> keyColumns = MarkdownTables.keyColumns(sourceKey, report, headings)
        int keyWidth = keyColumns.size()
        String composite = MarkdownTables.compositeKey(cells, keyWidth)
        // What the plan wrote, not what it normalises to: a reader looking for "Lamar Jackson" should not
        // have to recognise himself in LAMARJACKSON.
        String shown = (0..<keyWidth).collect { it < cells.size() ? clean(cells[it]) : null }
                .findAll().join(' ')
        if (!composite.replace('|', '')) {
            return []
        }
        List<Map<String, String>> matched = MarkdownTables.rowsMatching(report, keyColumns, composite)
        if (!matched) {
            return ["line $line: '$shown' is not on the $source board"]
        }
        // A key that picks out several rows picks out none. Resolving it to whichever came last is how a
        // plan citing pick 13 of the outlook was answered from round 13 — sometimes a wrong failure,
        // sometimes a wrong pass, and never a question anybody asked.
        if (matched.size() > 1) {
            return ["line $line: '$shown' matches ${matched.size()} rows of the $source board keyed on " +
                            "${keyColumns.join('+')}, so it names no one row — name a key with " +
                            '<!-- source: ' + source + ' key=' + keyColumns.join('+') + '+... -->' as String]
        }
        Map<String, String> row = matched.first()

        List<String> failures = []
        headings.eachWithIndex { String heading, int column ->
            if (column < keyWidth || column >= cells.size() || !row.containsKey(heading)) {
                return
            }
            String cited = clean(cells[column])
            String actual = row[heading]
            if (cited && !matches(cited, actual)) {
                failures << "line $line: $shown $heading is $actual on the board, cited as $cited"
            }
        }
        failures
    }

    /**
     * A report as its rows in file order, cached because a document cites one many times.
     *
     * <b>Unkeyed.</b> Which column names a row is the citation's business — see
     * {@link MarkdownTables#keyColumns} — and indexing here is what produced the PLAYER and OWNER special
     * cases: two column names hardcoded because they were the two that happened to be wanted.
     */
    private static List<Map<String, String>> report(File yearDir, String source,
                                                    Map<String, List<Map<String, String>>> cache) {
        String path = new File(yearDir, "${source}.tsv").path
        if (cache.containsKey(path)) {
            return cache[path]
        }
        File file = new File(path)
        List<Map<String, String>> rows = null
        if (file.exists()) {
            // A report may open with commentary — which team it is for, what its roster already scores —
            // before the single table that is the report proper.
            List<String> lines = file.readLines().dropWhile { it.startsWith('#') || !it.trim() }
            if (lines) {
                List<String> headings = lines[0].split('\t', -1) as List
                rows = []
                lines.drop(1).each { String line ->
                    if (line.trim()) {
                        List<String> values = line.split('\t', -1) as List
                        Map<String, String> row = [:]
                        headings.eachWithIndex { String heading, int i ->
                            row[heading] = i < values.size() ? values[i].trim() : ''
                        }
                        rows << row
                    }
                }
            }
        }
        cache[path] = rows
        rows
    }

    private static boolean isTableRow(String line) { MarkdownTables.isTableRow(line) }

    private static boolean isDivider(List<String> cells) { MarkdownTables.isDivider(cells) }

    private static List<String> cells(String line) { MarkdownTables.cells(line) }

    /** Strip the markdown a figure may be dressed in, so **$76** and 76 are the same number. */
    static String clean(String cell) { MarkdownTables.clean(cell) }

    /** Numbers compare as numbers so 0.26 and .26 agree; everything else compares as text. */
    static boolean matches(String cited, String actual) { MarkdownTables.matches(cited, actual) }
}
