package ff.run

import ff.run.fuad.ReportManifest

/**
 * Check that a strategy document reasons only from a current board.
 *
 * A plan is written against one auction board and then the model moves. Nothing about a stale figure looks
 * stale: prices that are half a season out of date read exactly like prices that are not, and a plan is
 * worst affected precisely where the model changed most. Worse, a plan that reaches behind the board for a
 * rule or a constant argues a point the board has already priced in, and pays for it twice.
 *
 * So three things are checked, and each is a different way of getting the same thing wrong.
 *
 * <b>Provenance.</b> The document names the model it was written against; every report it cites must have
 * been generated by that model. This is the one that catches wholesale drift, including in prose that no
 * checker can read.
 *
 * <b>Figures.</b> Any table under a {@code <!-- source: type -->} marker is looked up in that report,
 * column by column, so a transcription slip or a hand-edited number is caught and named.
 *
 * <b>Boundary.</b> Nothing in the document may name a model internal, an input file, or a source path. A
 * figure that needs one of those is a report column that does not exist yet, and the fix is to add it to
 * the board rather than to quote it into the plan.
 *
 * See docs/STRATEGY.md.
 */
class StrategyCheck {

    /** Model internals and inputs a plan must not reason from. Matched case insensitively, as whole words. */
    static final List<String> FORBIDDEN = [
            'AuctionValuation', 'PointsCurve', 'StarterRequirements', 'ByeWeeks', 'ScoringRules',
            'FranchiseSalaryCalculator', 'FranchiseTagIdentifier', 'PlayerSalaryCalculator',
            'NflverseStatsLoader', 'FuadValuationLoader',
            'SPEND_RATE', 'MARKET_WEIGHT', 'MARKET_SHARE', 'PRICE_STEEPNESS', 'ROOKIE_BUDGET_SHARE',
            'TAGGED_AVAILABILITY', 'REALISED_SEASONS', 'ROSTERED_DEPTH',
            'rules.json', 'league.json', 'rosters.json', 'players.json', 'player_stats.tsv',
            'projected_scores.json', 'rosters_post_draft.json', 'rosters_end_of_year.json',
            'redraft_rankings_half_ppr.csv', 'dynasty_rankings_ppr.csv',
            'nflverse', 'fantasypros',
    ].asImmutable() as List<String>

    /** Paths a plan must not cite, being the model's own workings rather than its output. */
    static final List<String> FORBIDDEN_PATHS = ['src/', 'docs/'].asImmutable() as List<String>

    private static final String MODEL_MARKER = /<!--\s*model:\s*(\S+)\s*-->/
    private static final String SOURCE_MARKER = /<!--\s*source:\s*(\S+)\s*-->/

    static void main(String[] args) {
        if (args.length < 1 || args.length > 2) {
            System.err.println('Usage: StrategyCheck <document.md> [reports-dir]')
            System.exit(2)
        }
        File document = new File(args[0])
        if (!document.exists()) {
            System.err.println("No such document: $document")
            System.exit(2)
        }
        File reportsDir = new File(args.length > 1 ? args[1] : 'reports')

        List<String> failures = check(document, reportsDir)
        if (failures) {
            println "FAIL  $document"
            failures.each { println "  $it" }
            System.exit(1)
        }
        println "OK    $document"
    }

    /** Every way the document disagrees with the board, in the order they appear. */
    static List<String> check(File document, File reportsDir) {
        List<String> lines = document.readLines()
        List<String> failures = []
        failures.addAll(checkBoundary(lines))

        String model = declaredModel(lines)
        if (!model) {
            failures << "no model declared: add a <!-- model: ${ReportManifest.currentModel()} --> marker"
            return failures
        }

        File yearDir = reportDirectory(document, reportsDir)
        if (!yearDir?.isDirectory()) {
            failures << "no reports directory for this document under $reportsDir"
            return failures
        }
        Map<String, ReportManifest.Stamp> stamps = ReportManifest.read(yearDir)
        if (!stamps) {
            failures << "$yearDir holds no ${ReportManifest.FILE_NAME}: regenerate the reports"
            return failures
        }

        failures.addAll(checkTables(lines, model, yearDir, stamps))
        failures
    }

    /** The `<!-- model: sha -->` the document was written against. */
    static String declaredModel(List<String> lines) {
        for (String line : lines) {
            def matcher = line =~ MODEL_MARKER
            if (matcher.find()) {
                return matcher.group(1)
            }
        }
        null
    }

    /**
     * Which season's reports the document is about, taken from a four digit year in its name.
     *
     * Naming the year rather than declaring it keeps one less thing to hand-maintain, and a plan that does
     * not say which season it is for has a bigger problem than this check.
     */
    private static File reportDirectory(File document, File reportsDir) {
        def matcher = document.name =~ /(\d{4})/
        matcher.find() ? new File(reportsDir, matcher.group(1)) : null
    }

    private static List<String> checkBoundary(List<String> lines) {
        List<String> failures = []
        lines.eachWithIndex { String line, int index ->
            // The markers themselves name report types and paths, and are the sanctioned way to do so.
            if (line.trim().startsWith('<!--')) {
                return
            }
            FORBIDDEN.each { String term ->
                if (line =~ /(?i)(?<![\w.\/])${java.util.regex.Pattern.quote(term)}(?![\w])/) {
                    failures << "line ${index + 1}: reasons from '$term', which is a model input, " +
                            'not a model output'
                }
            }
            FORBIDDEN_PATHS.each { String path ->
                if (line.contains(path)) {
                    failures << "line ${index + 1}: cites '$path', which is the model's workings, " +
                            'not its output'
                }
            }
        }
        failures
    }

    /**
     * Verify every table under a source marker against the report it names.
     *
     * The table's first column names the report column its rows are keyed by, and every other heading that
     * matches a report column is checked. Headings that match nothing are the plan's own commentary and are
     * left alone, so a table can carry a note or a running total without having to be understood here.
     */
    private static List<String> checkTables(List<String> lines, String model, File yearDir,
                                            Map<String, ReportManifest.Stamp> stamps) {
        List<String> failures = []
        Set<String> provenanceChecked = []
        Map<String, Map<String, Map<String, String>>> cache = [:]
        String source = null
        List<String> headings = null

        for (int i = 0; i < lines.size(); i++) {
            String line = lines[i]
            def sourceMatcher = line =~ SOURCE_MARKER
            if (sourceMatcher.find()) {
                source = sourceMatcher.group(1)
                headings = null
                if (provenanceChecked.add(source)) {
                    failures.addAll(checkProvenance(source, model, stamps, i + 1))
                }
                continue
            }
            if (!source) {
                continue
            }
            if (!isTableRow(line)) {
                // A blank line between the marker and its table is fine; anything else ends the table.
                if (line.trim() && headings != null) {
                    source = null
                }
                continue
            }
            List<String> cells = cells(line)
            if (headings == null) {
                headings = cells
                continue
            }
            if (isDivider(cells)) {
                continue
            }
            failures.addAll(checkRow(source, yearDir, headings, cells, i + 1, cache))
        }
        failures
    }

    private static List<String> checkProvenance(String source, String model,
                                                Map<String, ReportManifest.Stamp> stamps, int line) {
        ReportManifest.Stamp stamp = stamps[source]
        if (!stamp) {
            return ["line $line: cites '$source', which has not been generated for this season"]
        }
        if (stamp.dirty) {
            return ["line $line: '$source' was generated from an uncommitted model ($stamp.model), " +
                            'so nothing can be checked against it']
        }
        if (stamp.sha() != model) {
            return ["line $line: written against model $model but '$source' was generated by " +
                            "${stamp.sha()} — regenerate the report and revisit the plan"]
        }
        []
    }

    private static List<String> checkRow(String source, File yearDir, List<String> headings,
                                         List<String> cells, int line,
                                         Map<String, Map<String, Map<String, String>>> cache) {
        Map<String, Map<String, String>> report = report(yearDir, source, cache)
        if (report == null) {
            return ["line $line: no report file for '$source'"]
        }
        String keyColumn = headings ? headings[0] : null
        String key = cells ? clean(cells[0]) : null
        if (!key) {
            return []
        }
        Map<String, String> row = report[key]
        if (row == null) {
            return ["line $line: '$key' is not on the $source board"]
        }
        if (!row.containsKey(keyColumn)) {
            return ["line $line: '$keyColumn' is not a column of $source"]
        }

        List<String> failures = []
        headings.eachWithIndex { String heading, int column ->
            if (column == 0 || column >= cells.size() || !row.containsKey(heading)) {
                return
            }
            String cited = clean(cells[column])
            String actual = row[heading]
            if (cited && !matches(cited, actual)) {
                failures << "line $line: $key $heading is $actual on the board, cited as $cited"
            }
        }
        failures
    }

    /** A report as rows keyed by their first column, cached because a document cites one many times. */
    private static Map<String, Map<String, String>> report(File yearDir, String source,
                                                           Map<String, Map<String, Map<String, String>>> cache) {
        String path = new File(yearDir, "${source}.tsv").path
        if (cache.containsKey(path)) {
            return cache[path]
        }
        File file = new File(path)
        Map<String, Map<String, String>> rows = null
        if (file.exists()) {
            // A report may open with commentary — which team it is for, what its roster already scores —
            // before the single table that is the report proper.
            List<String> lines = file.readLines().dropWhile { it.startsWith('#') || !it.trim() }
            if (lines) {
                List<String> headings = lines[0].split('\t', -1) as List
                rows = [:]
                lines.drop(1).each { String line ->
                    if (line.trim()) {
                        List<String> values = line.split('\t', -1) as List
                        Map<String, String> row = [:]
                        headings.eachWithIndex { String heading, int i ->
                            row[heading] = i < values.size() ? values[i].trim() : ''
                        }
                        rows[row[headings[0]]] = row
                        // Boards are keyed by name for a reader; PLAYER is the useful key on salaries.
                        if (row.containsKey('PLAYER')) {
                            rows[row['PLAYER']] = row
                        }
                        if (row.containsKey('OWNER')) {
                            rows[row['OWNER']] = row
                        }
                    }
                }
            }
        }
        cache[path] = rows
        rows
    }

    private static boolean isTableRow(String line) { line.trim().startsWith('|') }

    private static boolean isDivider(List<String> cells) {
        cells.every { it.trim() ==~ /:?-{2,}:?/ }
    }

    private static List<String> cells(String line) {
        String trimmed = line.trim()
        trimmed = trimmed.replaceFirst(/^\|/, '').replaceFirst(/\|$/, '')
        trimmed.split(/\|/, -1).collect { it.trim() } as List<String>
    }

    /** Strip the markdown a figure may be dressed in, so **$76** and 76 are the same number. */
    static String clean(String cell) {
        cell?.replaceAll(/[*`]/, '')?.replaceAll(/[$,]/, '')?.trim()
    }

    /** Numbers compare as numbers so 0.26 and .26 agree; everything else compares as text. */
    static boolean matches(String cited, String actual) {
        if (cited.equalsIgnoreCase(actual)) {
            return true
        }
        try {
            return new BigDecimal(cited).compareTo(new BigDecimal(actual)) == 0
        } catch (NumberFormatException ignored) {
            return false
        }
    }
}
