#!/usr/bin/env bash
# Checks a strategy document against the board it claims to be written from.
#
# Verifies that every report it cites was generated by the model it names, that every figure in its
# tables matches that report, and that it reasons from no model input. See docs/STRATEGY.md.
#
# Usage:
#   ./check_strategy.sh <document.md> [reports-dir]
#
# Examples:
#   ./check_strategy.sh strategy/2026-draft-plan.md
#   ./check_strategy.sh strategy/2026-draft-plan.md reports
set -euo pipefail

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$DIR"

CLASSPATH_FILE="target/classpath.txt"

if [[ ! -f "$CLASSPATH_FILE" || "pom.xml" -nt "$CLASSPATH_FILE" ]]; then
    ./mvnw -q compile dependency:build-classpath -Dmdep.outputFile="$CLASSPATH_FILE"
else
    ./mvnw -q compile
fi

java -cp "target/classes:$(cat "$CLASSPATH_FILE")" ff.run.StrategyCheck "$@"
